[workspace]

members = [
    "sails-db",
    "sails-bin",
]

[patch.crates-io]
# This workaround should be removed once the all the crates are updated
askama = { git = "https://github.com/djc/askama", branch = "main" }
askama_rocket = { git = "https://github.com/djc/askama", branch = "main" }
