[workspace]

members = [
    "sails-db",
    "sails-bin"
]

[patch.crates-io]
rocket = { git = "https://github.com/SergioBenitez/Rocket" }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket" }
