[package]
name = "sails-bin"
version = "0.1.0"
authors = ["Harry Ying <lexugeyky@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "^1.7"
comrak = "0.10"
check-if-email-exists = "0.8"
rocket = { version = "0.5.0-dev", features = ["secrets"] }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
diesel = { version = "^1.4", features = ["sqlite", "r2d2"] }
diesel_migrations = "^1.4"
sails-db = { path = "../sails-db" }
thiserror = "^1"
rust-embed="^5.9"
structopt = "^0.3"
# We need askama as the backend template engine because it is type safe, however, it doesn't work with rocket 0.5 yet.
# See also: https://github.com/djc/askama/pull/412
askama = { version = "^0.10", features = ["with-rocket", "mime", "mime_guess"]}
askama_rocket = "^0.10"

[dependencies.rocket_sync_db_pools]
version = "0.1.0-dev"
default-features = false
features = ["diesel_sqlite_pool"]
