on:
  push:
    branches:
      - '**'
  pull_request:

name: Build, test, bench, and continuous deployment

jobs:
  cachix:
    name: upload cachix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
      - uses: cachix/install-nix-action@v16
        # with:
        #  install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.6.0pre20211217_6e6e998/install
      - uses: cachix/cachix-action@v8
        if: ${{ github.event_name == 'push' }}
        with:
          name: flibrary
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      # Run the general flake checks
      - run: |
          nix flake update
          nix flake check -vL

  check:
    name: Build all feature permutations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}-check
      - run: sudo apt-get install gettext
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-all-features
          version: latest
          use-tool-cache: true
      - run: cargo build-all-features

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}-test
      - run: sudo apt-get install gettext
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  bench:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}-bench
      - run: sudo apt-get install gettext
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --no-run

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}-clippy
      - run: sudo apt-get install gettext
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy

  repo_dispatch:
    if: github.event_name == 'push'
    name: Create repository dispatch
    runs-on: ubuntu-latest
    needs:
      [cachix, check, test, bench, clippy]
    steps:
      - name: Create repository dispatch event
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh api repos/flibrary/infra/dispatches \
              --raw-field event_type=sails_trigger_deploy
